all:
	pdflatex doc.tex
	bibtex doc.aux
	pdflatex doc.tex
	pdflatex doc.tex
	rm *.aux
#	rm *.lof
	rm *.log
#	rm *.lot
	rm *.bbl
	rm *.blg
	rm *.toc
	rm *.out
clean:
	rm *.aux
#	rm *.lof
	rm *.log
#	rm *.lot
	rm *.bbl
	rm *.blg
	rm *.toc
	rm *.out
